// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjWD4b7PvRxJbazSVetilTeKEUHAK8Us',
    appId: '1:250823763644:web:034b7c18f801f1bec652b9',
    messagingSenderId: '250823763644',
    projectId: 'howboutyou',
    authDomain: 'howboutyou.firebaseapp.com',
    storageBucket: 'howboutyou.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArOTpnwn1mtWUntDD7fma6l4WsviPEbU',
    appId: '1:250823763644:android:c27041245ef81e9cc652b9',
    messagingSenderId: '250823763644',
    projectId: 'howboutyou',
    storageBucket: 'howboutyou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-dDvlbAYFRboy9me5GqBwUJ4HCGCpbo',
    appId: '1:250823763644:ios:a02f8f773043150cc652b9',
    messagingSenderId: '250823763644',
    projectId: 'howboutyou',
    storageBucket: 'howboutyou.appspot.com',
    iosClientId: '250823763644-q649itmv81lu7fi40q4fqco5g377r8o8.apps.googleusercontent.com',
    iosBundleId: 'com.howboutyou.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-dDvlbAYFRboy9me5GqBwUJ4HCGCpbo',
    appId: '1:250823763644:ios:a02f8f773043150cc652b9',
    messagingSenderId: '250823763644',
    projectId: 'howboutyou',
    storageBucket: 'howboutyou.appspot.com',
    iosClientId: '250823763644-q649itmv81lu7fi40q4fqco5g377r8o8.apps.googleusercontent.com',
    iosBundleId: 'com.howboutyou.app',
  );
}
