# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: howboutyou

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10'
          channel: 'stable'
          
      - name: check version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        
      - name: Confirm the build succeeds
        run: flutter create .
        run: flutter build web
